name: daily-fleece-local-dev

services:
  mongodb:
    image: mongo:8.3
    ports:
      - '${LOCAL_DEV_MONGODB_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_DATABASE: daily_fleece
      GLIBC_TUNABLES: glibc.cpu.hwcaps=-SHSTK
    volumes:
      - 'daily-fleece-local-dev:/data/db'
      - ./src/main/resources/db/migration/V1__init.js:/docker-entrypoint-initdb.d/01_init.js:ro

volumes:
  daily-fleece-local-dev:
    name: '${LOCAL_DEV_MONGO_VOLUME:-daily-fleece-local-dev}'
