spring.docker.compose.enabled=true
spring.docker.compose.file=compose.local-dev.yml,compose.observability.yml
spring.docker.compose.lifecycle-management=start-only
server.port=${BACKEND_PORT:8080}
management.tracing.sampling.probability=1.0
